---
title: "snow melt analysis"
author: "Mariel Jones"
date: "2023-05-12"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("astsa")
library(astsa)
library(dplyr)
library(tidyverse)
```

```{r}
SWE = read.csv('D:/1_DesktopBackup/Feng Research/0_MEF Snow Hydology/mef-snowhydro/Data and Codes/Cleaned Data/SWE_FROST_yearSummary.csv')
SWE
```

```{r}
#Linear model of frost from canopy
SWE$FROST.1.sqrt = sqrt(SWE$FROST.1)
frostMod = lm('FROST.1.sqrt ~ 0+OLS.Prediction.Ring.5', data = SWE)
summary(frostMod)
plot(frostMod)
```

```{r}
#Linear model of frost from canopy and snow
frostSWEMod = lm('FROST.1.sqrt ~ OLS.Prediction.Ring.5*SWE_cm', data = SWE)
summary(frostSWEMod)
plot(frostSWEMod)
```

```{r}
#Linear model of frost from snow
SWEMod = lm('FROST.1.sqrt ~ SWE_cm', data = SWE)
summary(SWEMod)
plot(SWEMod)
```


```{r}
#nested f test
anova(frostMod, frostSWEMod, test='F') #The addition of SWE does not significantly increase our prediction of frost compared to LAI
```

```{r}
plot(x = SWE$OLS.Prediction.Ring.5, y = SWE$FROST.1.sqrt)
lines(SWE$OLS.Prediction.Ring.5, frostMod$fitted.values)
```