title: "snow time series analysis"
author: "Mariel Jones"
date: "2023-05-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#install.packages("astsa")
library(astsa)
library(dplyr)
library(tidyverse)
```

```{r}
setwd("C:/Users/marie/Desktop/mef-snowhydro")
### Import Snow Data
s2data = read.csv("./Data and Codes/Cleaned Data/01_cleanedsnowdataS2.csv",
                  header = TRUE,
                  sep = ",",
                  #col.names = c("time", "northing", "easting", "zones", "stakes", 
                  #              "aspect", "slope", "watershed")
                  )
s2data = na.omit(s2data)
s6data = read.csv("./Data and Codes/Cleaned Data/01_cleanedsnowdataS6.csv",
                  header = TRUE,
                  sep = ",",
                  #col.names = c("time", "northing", "easting", "zones", "stakes",
                  #              "aspect", "slope", "watershed")
                  )
s6data = na.omit(s6data)
```

```{r}
#Check data
head(s2data)
```

```{r}
#Groupby date and zone -- eliminate stake names
s2data_grouped  = s2data %>%
  group_by(time, zones) %>%
  summarize(mean_depth = mean(depths))

head(s2data_grouped)

s6data_grouped  = s6data %>%
  group_by(time, zones) %>%
  summarize(mean_depth = mean(depths))

head(s6data_grouped)
```

## Run Repeated Measures test for each of S2 and S6 - compare between zones averaged by time and inter-zone across time

```{r}
#Set time series
s2_depths = ts(s2data_grouped$mean_depth)
s2_times = ts(s2data_grouped$time)
s2_zones = ts(s2data_grouped$zones)

s6_depths = ts(s6data_grouped$mean_depth)
s6_times = ts(s6data_grouped$time)
s6_zones = ts(s6data_grouped$zones)
```

```{r}
#Run S2 Repeated Measures ANOVA
Y = s2data$depths
aov.p = aov(Y ~ (factor(zones)*factor(time))+Error(factor(stakes)), s2data)
summary(aov.p)

#Results -- Betweens are not significant, as we expected. There is no sig difference between the zones. Within a zone, however, there is a significant trend with time (as we would hope) and there is a significant interaction with zone and time, so even though the overall means might be different there is a slight difference in slopes. 
```
```{r}
#Run S2 Repeated Measures ANOVA
Y = s6data$depths
aov.p = aov(Y ~ (factor(zones)*factor(time))+Error(factor(stakes)), s6data)
summary(aov.p)

#Results - Between the zones there is a significant difference (yay!) and within the zones there is a signifcant relationship with time, expected, and a slight difference in slopes, although not as significant as the S2 data. 
```
## Compare the zones between catchments -- i.e. S2 bog to S6 bog, S2 upland to S6 upland, etc. 

```{r}
alldata = rbind(s2data, s6data)

bog = alldata %>%
  filter(zones == 'Bog')

lagg = alldata %>%
  filter(zones == 'Lagg')

upland = alldata %>%
  filter(zones == 'Upland')
```

```{r}
#Run Upland Repeated Measures ANOVA
Y = upland$depths
aov.p = aov(Y ~ (factor(watershed)*factor(time))+Error(factor(stakes)), upland)
summary(aov.p)
```

```{r}
#Run Lagg Repeated Measures ANOVA
Y = lagg$depths
aov.p = aov(Y ~ (factor(watershed)*factor(time))+Error(factor(stakes)), lagg)
summary(aov.p)
```

```{r}
#Run Bog Repeated Measures ANOVA
Y = bog$depths
aov.p = aov(Y ~ (factor(watershed)*factor(time))+Error(factor(stakes)), bog)
summary(aov.p)
```





















```{r}
### Import LAI data 
s2lai = read.csv("D:/1_DesktopBackup/Feng Research/0_MEF Snow Hydology/mef-snowhydro/Data and Codes/Cleaned Data/S2_winterLAI_calibrated.csv", 
                 header = TRUE, 
                 sep = ",")
s6lai = read.csv("D:/1_DesktopBackup/Feng Research/0_MEF Snow Hydology/mef-snowhydro/Data and Codes/Cleaned Data/S6_winterLAI_calibrated.csv", 
                 header = TRUE, 
                 sep = ",")

lai = rbind(s2lai, s6lai)
```

```{r}
summary(lai)
```

```{r}
two.way <- aov(OLS.Prediction.Ring.5 ~ Zone + Watershed, data = lai)

summary(two.way)
```
```{r}
tukey.plot.aov <- aov(OLS.Prediction.Ring.5 ~ Zone:Watershed, data=lai)
```


```{r}
tukey.plot.test <- TukeyHSD(tukey.plot.aov)
```

```{r}
plot(tukey.plot.test, las = 1, cex.axis=0.4)
```
















